name: Trigger Vercel Deployment

on:
  push:
    branches: [ main ]

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Vercel Deployment
      run: |
        echo "Push detected - Vercel should auto-deploy via webhook"
        echo "Check Vercel dashboard for deployment status"
        echo "Deployment URL: https://v0-ruined-clothing-website.vercel.app" 